spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: liyahui360@163.com #发送邮件的邮箱地址
    password: IWQACOMBGHGKSQIT #客户端授权码，不是邮箱密码，这个在邮箱设置里面自动生成的
    properties.mail.smtp.port: 994 #端口号465或587
    from: liyahui360@163.com # 发送邮件的地址，和上面username一致
    to: 269780193@qq.com # 接收人邮箱
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jiedai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
server:
  servlet:
    context-path: /test
    jsp:
      init-parameters:
        development: true
  port: 8989
#mybatis:
#  mapper-locations: classpath:com/baizhi/mapper/*.xml
#  type-aliases-package: com.baizhi.entity

